name: Test Gmail Integration

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]  # Or your default branch

jobs:
  test-gmail:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
    
    - name: Test Gmail Integration
      env:
        GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
        GMAIL_TOKEN_DATA: ${{ secrets.GMAIL_TOKEN_DATA }}
        PYTHONUNBUFFERED: 1  # This ensures Python output is not buffered
      run: |
        echo "Starting Gmail integration test..."
        python -c "
        import logging
        from gmail_utils import get_gmail_service
        try:
            service = get_gmail_service()
            print('Gmail service built and tested successfully!')
        except Exception as e:
            print(f'Test failed: {str(e)}')
            exit(1)
        " 